"""add_chat_and_usage_models

Revision ID: badc0c700a95
Revises: f30ee8f53d73
Create Date: 2026-05-15 19:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'badc0c700a95'
down_revision: Union[str, None] = 'f30ee8f53d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('external_user_id', sa.String(length=150), nullable=True),
    sa.Column('collection_uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_chat_sessions_session_uuid'), 'chat_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('idx_chat_sessions_tenant_uuid'), 'chat_sessions', ['tenant_uuid'], unique=False)
    op.create_index(op.f('idx_chat_sessions_external_user_id'), 'chat_sessions', ['external_user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('message_uuid', sa.String(length=36), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatrole'), nullable=False),
    sa.Column('content', sa.LongText(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_chat_messages_message_uuid'), 'chat_messages', ['message_uuid'], unique=True)
    op.create_index(op.f('idx_chat_messages_session_uuid'), 'chat_messages', ['session_uuid'], unique=False)
    op.create_index(op.f('idx_chat_messages_tenant_uuid'), 'chat_messages', ['tenant_uuid'], unique=False)

    op.create_table('retrieval_logs',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('retrieval_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('retrieved_chunks', sa.JSON(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_retrieval_logs_retrieval_uuid'), 'retrieval_logs', ['retrieval_uuid'], unique=True)
    op.create_index(op.f('idx_retrieval_logs_tenant_uuid'), 'retrieval_logs', ['tenant_uuid'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('usage_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('api_key_uuid', sa.String(length=36), nullable=True),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('embedding_model', sa.String(length=150), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='usagestatus'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_usage_logs_usage_uuid'), 'usage_logs', ['usage_uuid'], unique=True)
    op.create_index(op.f('idx_usage_logs_tenant_uuid'), 'usage_logs', ['tenant_uuid'], unique=False)
    op.create_index(op.f('idx_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)

    op.create_table('model_configs',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('config_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('top_p', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_model_configs_config_uuid'), 'model_configs', ['config_uuid'], unique=True)

    op.create_table('answer_feedback',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('feedback_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('session_uuid', sa.String(length=36), nullable=True),
    sa.Column('message_uuid', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_answer_feedback_feedback_uuid'), 'answer_feedback', ['feedback_uuid'], unique=True)
    op.create_index(op.f('idx_answer_feedback_tenant_uuid'), 'answer_feedback', ['tenant_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_feedback')
    op.drop_table('model_configs')
    op.drop_table('usage_logs')
    op.drop_table('retrieval_logs')
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
