"""initial_document_and_collection_models

Revision ID: f30ee8f53d73
Revises: 
Create Date: 2026-05-15 19:25:35.469642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30ee8f53d73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='tenantstatus'), nullable=False),
    sa.Column('default_model', sa.String(length=150), nullable=True),
    sa.Column('default_embedding_model', sa.String(length=150), nullable=True),
    sa.Column('monthly_quota_tokens', sa.BigInt(), nullable=True),
    sa.Column('monthly_quota_requests', sa.BigInt(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('idx_tenants_tenant_uuid'), 'tenants', ['tenant_uuid'], unique=True)
    
    op.create_table('api_clients',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='apiclientstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_api_clients_client_uuid'), 'api_clients', ['client_uuid'], unique=True)
    op.create_index(op.f('idx_api_clients_tenant_uuid'), 'api_clients', ['tenant_uuid'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('key_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='apikeystatus'), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_api_keys_key_uuid'), 'api_keys', ['key_uuid'], unique=True)
    op.create_index(op.f('idx_api_keys_tenant_uuid'), 'api_keys', ['tenant_uuid'], unique=False)
    op.create_index(op.f('idx_api_keys_client_uuid'), 'api_keys', ['client_uuid'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('collection_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vector_collection_name', sa.String(length=200), nullable=False),
    sa.Column('metadata_schema', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='collectionstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_collections_collection_uuid'), 'collections', ['collection_uuid'], unique=True)
    op.create_index(op.f('idx_collections_tenant_uuid'), 'collections', ['tenant_uuid'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('document_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('collection_uuid', sa.String(length=36), nullable=False),
    sa.Column('external_document_id', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.BigInt(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_documents_document_uuid'), 'documents', ['document_uuid'], unique=True)
    op.create_index(op.f('idx_documents_tenant_uuid'), 'documents', ['tenant_uuid'], unique=False)
    op.create_index(op.f('idx_documents_collection_uuid'), 'documents', ['collection_uuid'], unique=False)
    op.create_index(op.f('idx_documents_external_document_id'), 'documents', ['external_document_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('version_uuid', sa.String(length=36), nullable=False),
    sa.Column('document_uuid', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_document_versions_version_uuid'), 'document_versions', ['version_uuid'], unique=True)
    op.create_index(op.f('idx_document_versions_document_uuid'), 'document_versions', ['document_uuid'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('collection_uuid', sa.String(length=36), nullable=False),
    sa.Column('document_uuid', sa.String(length=36), nullable=False),
    sa.Column('version_uuid', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('content', sa.MediumText(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(length=150), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_document_chunks_chunk_uuid'), 'document_chunks', ['chunk_uuid'], unique=True)
    op.create_index(op.f('idx_document_chunks_tenant_uuid'), 'document_chunks', ['tenant_uuid'], unique=False)
    op.create_index(op.f('idx_document_chunks_collection_uuid'), 'document_chunks', ['collection_uuid'], unique=False)
    op.create_index(op.f('idx_document_chunks_document_uuid'), 'document_chunks', ['document_uuid'], unique=False)

    op.create_table('indexing_jobs',
    sa.Column('id', sa.BigInt(), autoincrement=True, nullable=False),
    sa.Column('job_uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_uuid', sa.String(length=36), nullable=False),
    sa.Column('document_uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_indexing_jobs_job_uuid'), 'indexing_jobs', ['job_uuid'], unique=True)
    op.create_index(op.f('idx_indexing_jobs_tenant_uuid'), 'indexing_jobs', ['tenant_uuid'], unique=False)
    op.create_index(op.f('idx_indexing_jobs_document_uuid'), 'indexing_jobs', ['document_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexing_jobs')
    op.drop_table('document_chunks')
    op.drop_table('document_versions')
    op.drop_table('documents')
    op.drop_table('collections')
    op.drop_table('api_keys')
    op.drop_table('api_clients')
    op.drop_table('tenants')
    # ### end Alembic commands ###
